// Developer Express Code Central Example:
// How to customize PDF Viewer Ribbon
// 
// The following example shows how to customize PDF Viewer Ribbon.
// To accomplish
// this task, it is necessary to override the default PdfViewerControl's
// RibbonTemplate and add the required bar items to the newly defined
// RibbonControl.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E5091

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXSample.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
